name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Run Spotless Apply
        run: ./gradlew spotlessApply

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck
  
      - name: Run tests with Kover coverage
        run: |
          ./gradlew clean check
          echo "Kover reports generated at:"
          ls -R build/reports/kover || echo "No Kover reports found."

      - name: Extract and display coverage percentage
        run: |
          REPORT_PATH=$(find build/reports/kover -name "report.xml" | head -n 1)
          if [ -z "$REPORT_PATH" ]; then
            echo "Kover coverage report not found!"
            exit 1
          fi
          echo "Found Kover XML report at: $REPORT_PATH"
          
          # Display the content of the XML report for debugging
          echo "Content of $REPORT_PATH:"
          cat "$REPORT_PATH"

          # Extract line coverage percentage
          LINE_MISSED=$(xmllint --xpath 'string(//counter[@type="LINE"]/@missed)' "$REPORT_PATH")
          LINE_COVERED=$(xmllint --xpath 'string(//counter[@type="LINE"]/@covered)' "$REPORT_PATH")

          TOTAL_LINES=$((LINE_MISSED + LINE_COVERED))
          if [ "$TOTAL_LINES" -eq 0 ]; then
            echo "No lines found in the report. Is the project being tested?"
            exit 1
          fi

          PERCENTAGE=$(echo "scale=2; ($LINE_COVERED / $TOTAL_LINES) * 100" | bc)
          echo "Line coverage: $PERCENTAGE%"

          # Validate coverage percentage
          MINIMUM=50.0
          if (( $(echo "$PERCENTAGE < $MINIMUM" | bc -l) )); then
            echo "Coverage is below the minimum required: $MINIMUM%!"
            exit 1
          fi
          echo "Coverage validation passed with $PERCENTAGE%."

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Setup Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Raise infra
        run: make infrastructure/up

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Run Spotless Apply
        run: ./gradlew spotlessApply
  
      - name: Code linting
        run: ./gradlew spotlessCheck

      - name: Static analysis
        run: |
          ./gradlew pmdMain
          ./gradlew pmdTest

      - name: Run tests
        run: ./gradlew test

      - name: Build
        run: ./gradlew clean assemble
