name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Run tests and generate JaCoCo report
        run: |
          ./gradlew clean test jacocoTestReport
          echo "Searching for the JaCoCo XML report..."
          REPORT_PATH=$(find /reports/jacoco/test -name "*.xml" | head -n 1)
          if [ -z "$REPORT_PATH" ]; then
            echo "No XML report found in the directory."
            exit 1
          fi
          echo "Found report at: $REPORT_PATH"
          echo "Printing JaCoCo XML report content:"
          cat "$REPORT_PATH"

      - name: Validate Coverage
        run: |
          REPORT_PATH=$(find /reports/jacoco/test -name "*.xml" | head -n 1)
          if [ -z "$REPORT_PATH" ]; then
            echo "Coverage report not found."
            exit 1
          fi
          COVERAGE=$(grep -oP 'coverage="\K[0-9.]+' "$REPORT_PATH" | awk '{sum+=$1} END {print sum}')
          echo "Coverage detected: $COVERAGE%"
          if (( $(echo "$COVERAGE < 50.0" | bc -l) )); then
            echo "Coverage is below 50%! Failing the job."
            exit 1
          fi

      - name: Upload coverage report to Codacy
        run: |
          REPORT_PATH=$(find /home/runner/work/payments-api-test-coverage/payments-api-test-coverage/build/reports/tests/test -name "*.xml" | head -n 1)
          if [ -z "$REPORT_PATH" ]; then
            echo "No coverage report found to upload."
            exit 1
          fi
          curl -Ls https://coverage.codacy.com/get.sh | bash
          ./codacy-coverage-reporter report \
            --token ${{ secrets.CODACY_PROJECT_TOKEN }} \
            --coverage-reports "$REPORT_PATH"
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Setup Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Raise infra
        run: make infrastructure/up

      - name: Code linting
        run: ./gradlew spotlessCheck

      - name: Static analysis
        run: |
          ./gradlew pmdMain
          ./gradlew pmdTest

      - name: Run tests
        run: ./gradlew test

      - name: Build
        run: ./gradlew clean assemble
